services:
  redis:
    image: redis:alpine
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    hostname: api
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  tester:
    build:
      context: .
      dockerfile: Dockerfile.tester
    hostname: tester
    container_name: tester
    depends_on:
      - api
