services:
  redis:
    image: redis:alpine
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
